### ISSUE TITLE
Dropbox plugin has no file limitation and manually deleting doesn't sync

### ISSUE THREAD

**Issue by trendal** [Ubiquiti-App/UCRM-plugins#169]
I'm really happy about the reintroduced Dropbox backup file syncing.  I don't have a lot of Dropbox space so I was wishing the plugin had a feature to limit how many files were stored.

Since it doesn't I decided to deal with it myself.  I created a cron job that deletes any file in the backup directory that is older than 3 days.  It works, but Dropbox does not sync the delete action.  

Also, there must be some index somewhere because the UNMS web UI still lists the deleted backup files as available for download or to restore.  But if I try to download any backup that my cron job has deleted it errors with "file not found" of course because it's gone.  

Best fix would be to add a file count limit feature native in UNMS.
Next best would be to get Dropbox to sync the delete actions

Crutch at the moment is to keep a cron job active on one of my "always online" computers to delete (and properly sync) the files older than 3 days.  The only thing left is the indexes in UNMS that I have to manually delete from time to time.

crontab line:
0 0 * * * root find /home/unms/data/unms-backups/backups -maxdepth 1 -type f -mtime +2 -exec rm -f {} \;

**Comment by keksa** [comment]
Hello @trendal, the plugin actually does delete backups, that are no longer present. However it does not check the files, since it does not have access to them.
It uses the UNMS API to get the list of backups and then tries to synchronize them. If you want to delete older backups automatically, you should use UNMS API for that. Take a look at `https://your-unms-url.com/nms/api-docs/#/Backups`

**Comment by trendal** [comment]
alright... I'll have to work up a script then.

Thank you.
